### ISSUE TITLE
Link broken

### ISSUE THREAD

**Issue by iemcloudteam** [40net-cloud/fortinet-gcp-solutions#5]
Mentioned link below is broken. 

Read [here](https://github.com/40net-cloud/fortinet-gcp-solutions/blob/master/FortiGate/architectures/README.md#choosing-ha-architecture)[](https://github.com/40net-cloud/fortinet-gcp-solutions/tree/master/FortiGate/architectures/200-ha-active-passive-lb-sandwich#diagram) more about differences between different HA designs in Google Cloud.

**Comment by bartekmo** [comment]
I believe it's fixed now. If you can still see the issue, please let me know in which file. Thank you!
