### ISSUE TITLE
Broken Link in README.MD

### ISSUE THREAD

**Issue by craigenator** [40net-cloud/fortinet-gcp-solutions#6]
There is a broken link in the Readme for https://github.com/40net-cloud/fortinet-gcp-solutions/tree/master/FortiGate/architectures/200-ha-active-passive-lb-sandwich

It is in the "Active-Passive HA Design Options Comparison" section

Also the [Other FortiGate designs](https://github.com/40net-cloud/fortinet-gcp-solutions/blob/master/FortiGate/architectures/README.md) link does not work in the same Readme as described above

**Comment by bartekmo** [comment]
Fixed now. Thank you!
