### ISSUE TITLE
Suggestion for DMZ

### ISSUE THREAD

**Issue by Kelvinloucosta** [40net-cloud/fortinet-gcp-solutions#7]
Any ideas to add one more interface to DMZ, for example for external accesses?

**Comment by bartekmo** [comment]
If you want to have a separate zone to run your servers in, I'd create a separate VPC and go with the peered VPC design (https://github.com/40net-cloud/fortinet-gcp-solutions/tree/master/FortiGate/architectures/300-peered-security-hub). I don't see using an additional NIC (although technically possible) to bring any benefit. Unless I'm missing something.

If you really really want to have more interfaces, you could use the multilb module for deployment manager. There's an example on using it to deploy 8-nic cluster here: https://github.com/40net-cloud/fortinet-gcp-solutions/blob/master/FortiGate/architectures/200-ha-active-passive-lb-sandwich/deployment-manager/ha-ap-8nic-lb-sandwich.yaml

**Comment by Kelvinloucosta** [comment]
thanks @bartekmo I did that and it worked. Thanks a lot, can I use these files to install another firewall, like Sophos?
